### ISSUE TITLE
Avrdude-Rpi still uses Python

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/avrdude-rpi#5]
https://github.com/openenergymonitor/avrdude-rpi/blob/9258241b1cda2aca34f870ddb16167eb1c4972b6/autoreset#L1

Avrdude-rpi still uses Python not python3

**Comment by bwduncan** [comment]
Should be fixed by #4. Duplicate of #3

**Comment by borpin** [comment]
🤦‍♂️
